---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Desonstar Technology Co., LTD"
keywords:    "苏州德森斯特通信技术有限公司"
description: "Desonstar - 苏州德森斯特通信技术有限公司"
source_link: "https://desonstar.github.io/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#433F3C'
  white:     '#f8f8f8'
  purewhite:     '#ffffff'
  blue:      '#428bca'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

